name: Notify

on:
  schedule:
    - cron: '0 4 * * 5' # UTC (JST -9)

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Run
        run: go run -v ./...
